### ISSUE TITLE
[Question] Architectury support?

### ISSUE THREAD

**Issue by ThexXTURBOXx** [kikugie/Stonecutter-skill-issue-fix#6]
Actually, a few years ago, when working on Block Helper, I thought about making a similar project to Stonecutter.
So, it is very nice to see that someone already made that and I don't have to, thank you very much! :)

Now related to my question... I have an Architectury project: https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy
Is that also supported by Stonecutter?
I don't plan on merging all the versions into one, but at least for 1.16.5+, it would be very nice to only have to update a single codebase everytime.
Do you have any experiences with that, perhaps?

**Comment by kikugie** [comment]
Architectury is already supported, although usually in a different setup. 

There's [Jab125's example project](https://github.com/Jab125/multiloader-example-mod), as well as mods like [Elytra Trims](https://github.com/Kikugie/elytra-trims) and [YACL](https://github.com/isXander/YetAnotherConfigLib) using similar setups. These setups merge all loaders into the single src directory and use the comment processor to enable the correct code. (There's also a [wiki page](https://stonecutter.kikugie.dev/stonecutter/tips#architectury-setup) on this topic)

0.5 alpha versions have better support for the standard architectury setup, which is documented in the [github files](https://github.com/kikugie/stonecutter/tree/0.5/docs/stonecutter), but it's still being tested. If you want to use this approach, join the [discord server](https://discord.gg/TBgNUCfryS). It may be more confusing to set up due to few examples for now, but feedback is very appeciated.
